CREATE DATABASE SNAKE_ORDERS_DB;

CREATE FILE FORMAT _SNAKE_GLOBAL_TOOLS.STAGES.JSON_FORMAT
TYPE = JSON;


CREATE STAGE _SNAKE_GLOBAL_TOOLS.STAGES.STG_ORDERS
FILE_FORMAT = _SNAKE_GLOBAL_TOOLS.STAGES.JSON_FORMAT;

CREATE SCHEMA SNAKE_ORDERS_DB.RAW_DATA;

CREATE TABLE SNAKE_ORDERS_DB.RAW_DATA.RAW_CUSTOMERS_JSON (
    CONTENT VARIANT
);

CREATE TABLE SNAKE_ORDERS_DB.RAW_DATA.RAW_ORDERS_JSON (
    CONTENT VARIANT
);


CREATE SCHEMA SNAKE_ORDERS_DB.VALID_DATA;

CREATE TABLE SNAKE_ORDERS_DB.VALID_DATA.TD_CUSTOMERS (
    CUSTOMER_ID STRING,
    NAME STRING,
    EMAIL STRING,
    REGISTRATION_DATE TIMESTAMP,
    ADDRESS_STREET STRING,
    ADDRESS_CITY STRING,
    ADDRESS_ZIP_CODE NUMBER,
    LOYALTY_POINTS NUMBER
);

CREATE TABLE SNAKE_ORDERS_DB.VALID_DATA.TD_ORDERS (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_DATE TIMESTAMP,
    TOTAL_AMOUNT FLOAT,
    SHIPPING_METHOD STRING
);

CREATE TABLE SNAKE_ORDERS_DB.VALID_DATA.TD_ORDER_ITEMS (
    ORDER_ID STRING,
    PRODUCT_ID STRING,
    NAME STRING,
    QUANTITY NUMBER,
    PRICE FLOAT
);

