COPY INTO SNAKE_ORDERS_DB.RAW_DATA.RAW_CUSTOMERS_JSON
FROM @_SNAKE_GLOBAL_TOOLS.STAGES.STG_ORDERS/customers_data.json;


COPY INTO SNAKE_ORDERS_DB.RAW_DATA.RAW_ORDERS_JSON
FROM @_SNAKE_GLOBAL_TOOLS.STAGES.STG_ORDERS/orders_data.json;
