INSERT INTO SNAKE_ORDERS_DB.VALID_DATA.TD_CUSTOMERS (CUSTOMER_ID, NAME, EMAIL, REGISTRATION_DATE, ADDRESS_STREET, ADDRESS_CITY, ADDRESS_ZIP_CODE, LOYALTY_POINTS)
SELECT c.value:customer_id::STRING AS CUSTOMER_ID,
    c.value:name::STRING AS NAME,
    c.value:email::STRING AS EMAIL,
    c.value:registration_date::TIMESTAMP AS REGISTRATION_DATE,
    c.value:address:street::STRING AS ADDRESS_STREET,
    c.value:address:city::STRING AS ADDRESS_CITY,
    c.value:address:zip_code::STRING AS ADDRESS_ZIP_CODE,
    c.value:loyalty_points::NUMBER AS LOYALTY_POINTS
FROM SNAKE_ORDERS_DB.RAW_DATA.RAW_CUSTOMERS_JSON,
LATERAL FLATTEN(input => CONTENT) c;


INSERT INTO SNAKE_ORDERS_DB.VALID_DATA.TD_ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, SHIPPING_METHOD)
SELECT c.value:order_id::STRING AS ORDER_ID,
    c.value:customer_id::STRING AS CUSTOMER_ID,
    c.value:order_date::TIMESTAMP AS ORDER_DATE,
    c.value:total_amount::FLOAT AS TOTAL_AMOUNT,
    c.value:shipping_method::STRING AS SHIPPING_METHOD
FROM SNAKE_ORDERS_DB.RAW_DATA.RAW_ORDERS_JSON,
LATERAL FLATTEN(input => CONTENT) c;


INSERT INTO SNAKE_ORDERS_DB.VALID_DATA.TD_ORDER_ITEMS (ORDER_ID, PRODUCT_ID, NAME, QUANTITY, PRICE)
SELECT i.value:order_id::STRING AS ORDER_ID,
    i.value:product_id::STRING AS PRODUCT_ID,
    i.value:name::STRING AS NAME,
    i.value:quantity::NUMBER AS QUANTITY,
    i.value:price::FLOAT AS PRICE
FROM SNAKE_ORDERS_DB.RAW_DATA.RAW_ORDERS_JSON,
LATERAL FLATTEN(input => CONTENT:items) i;